In [1]:
#| default_exp trigonometry

In [2]:
#| export

import jax
import jax.numpy as jnp

In [3]:
#| export

from jaxtyping import Float

In [4]:
#| hide

jax.config.update("jax_enable_x64", True)
jax.config.update("jax_debug_nans", False)

In [5]:
#| hide

import jaxtyping


In [6]:

#| hide

%load_ext jaxtyping
%jaxtyping.typechecker beartype.beartype

## `trigonometry`: Trigonometry

This module provides basic trigonometric, vector, and linear algebra functions for triangular meshes. These are scalar or single-triangle operations designed to be vectorized across meshes using `jax.vmap`.

::: {.callout-note collapse="true"}
### Coding style notes

Throughout, we provide type signatures for all functions using [jaxtyping](https://docs.kidger.site/jaxtyping). We use `jnp` (= `jax.numpy`) instead of `numpy`, and follow JAX's functional programming paradigm (see [JAX — the sharp bits](https://docs.jax.dev/en/latest/notebooks/Common_Gotchas_in_JAX.html)).

:::

### Safe division

Degenerate configurations (zero-length edges, collapsed triangles) can make divisors vanish. `safe_divide` and `safe_normalize` guard against this so that BOTH the value and its gradient stay finite, and - unlike clipping the divisor to a fixed value - they are scale independent, so a small mesh is not mistaken for a degenerate one.


In [9]:
#| export

def safe_divide(numerator: jax.Array, denominator: jax.Array, fill: float = 0.0) -> jax.Array:
    """Divide, returning ``fill`` where the denominator is exactly zero.

    Both the value and its gradient stay finite at ``denominator == 0``: the division
    uses a denominator of 1 wherever the true denominator vanishes, so reverse-mode never
    differentiates ``x / 0`` (a bare ``jnp.where(d != 0, x / d, fill)`` would still produce
    a NaN gradient from the untaken branch).

    This is scale independent: a small-but-valid denominator is divided by faithfully rather than
    being treated as zero, and a genuine zero yields ``fill`` instead of a huge finite
    number. `numerator` broadcasts against `denominator` as usual.
    """
    nonzero = denominator != 0
    safe_denominator = jnp.where(nonzero, denominator, 1.0)
    return jnp.where(nonzero, numerator / safe_denominator, fill)


def safe_norm(x: Float[jax.Array, "... dim"], axis: int = -1) -> Float[jax.Array, "..."]:
    """Return ``|x|``, with a finite (zero) gradient where ``|x| == 0``.

    `jnp.linalg.norm` has a NaN gradient at the origin, which propagates into every
    quantity computed from edge lengths as soon as a single edge collapses.
    The sum of squares is guarded before the square root instead.
    """
    sq = jnp.sum(x**2, axis=axis)
    nonzero = sq > 0
    return jnp.where(nonzero, jnp.sqrt(jnp.where(nonzero, sq, 1.0)), 0.0)


def safe_normalize(x: Float[jax.Array, "... dim"], axis: int = -1) -> Float[jax.Array, "... dim"]:
    """Return ``x / |x|``, or the zero vector where ``|x| == 0``.

    NaN-gradient-safe and scale independent (see `safe_divide`). The sum of squares is
    guarded directly rather than going through `jnp.linalg.norm`, whose gradient is itself
    NaN at the origin.
    """
    sq = jnp.sum(x**2, axis=axis, keepdims=True)
    nonzero = sq > 0
    return jnp.where(nonzero, x / jnp.sqrt(jnp.where(nonzero, sq, 1.0)), 0.0)

In [10]:
#| hide

# safe_divide / safe_normalize: value AND gradient finite at (and near) zero, scale-free
assert safe_divide(jnp.array(3.0), jnp.array(2.0)) == 1.5
assert safe_divide(jnp.array(3.0), jnp.array(0.0)) == 0.0
assert safe_divide(jnp.array(3.0), jnp.array(0.0), fill=7.0) == 7.0
# a valid small denominator is NOT treated as zero (this is the B16 scale bug)
assert jnp.allclose(safe_divide(jnp.array(1e-13), jnp.array(1e-13)), 1.0)

# gradient is finite at an exact zero denominator (a bare where would give NaN)
gnum, gden = jax.grad(safe_divide, argnums=(0, 1))(jnp.array(1.0), jnp.array(0.0))
assert jnp.isfinite(gnum) and jnp.isfinite(gden)

# safe_norm agrees with jnp.linalg.norm, but has a finite gradient at the origin
xs = jnp.array([[3., 4.], [1e-4, 0.], [0., 0.]])
assert jnp.allclose(safe_norm(xs), jnp.linalg.norm(xs, axis=-1))
assert jnp.isfinite(jax.jacobian(safe_norm)(jnp.zeros(3))).all()
assert not jnp.isfinite(jax.jacobian(lambda x: jnp.linalg.norm(x))(jnp.zeros(3))).all()  # the trap it avoids

# safe_normalize returns a unit vector, or 0 for the zero vector, with finite gradient
assert jnp.allclose(safe_normalize(jnp.array([3., 4.])), jnp.array([0.6, 0.8]))
assert jnp.allclose(safe_normalize(jnp.zeros(3)), jnp.zeros(3))
g = jax.jacobian(safe_normalize)(jnp.zeros(3))
assert jnp.isfinite(g).all()
# batched: unit vectors, and 0 for the zero row; scale independent for realistic magnitudes
out = safe_normalize(xs)
assert jnp.allclose(out[0], jnp.array([0.6, 0.8])) and jnp.allclose(out[1], jnp.array([1., 0.])) and jnp.allclose(out[2], 0.)

### Triangle areas and circumcenters

In [11]:
#| export

def get_circumcenter(a: Float[jax.Array, " dim"],
                     b: Float[jax.Array, " dim"],
                     c: Float[jax.Array, " dim"]) -> Float[jax.Array, " dim"]:
    """Circumcenter of triangle with vertices a, b, c via barycentric coordinates.

    Parameters
    ----------
    a, b, c : Float[Array, "dim"]
        Triangle vertex positions.

    Returns
    -------
    Float[Array, "dim"]
        Circumcenter coordinates.
    """
    la, lb, lc = jnp.linalg.norm(b - c), jnp.linalg.norm(c - a), jnp.linalg.norm(a - b)
    ba = la**2 * (lb**2 + lc**2 - la**2)
    bb = lb**2 * (lc**2 + la**2 - lb**2)
    bc = lc**2 * (la**2 + lb**2 - lc**2)
    return safe_divide(ba * a + bb * b + bc * c, ba + bb + bc)


def get_oriented_triangle_area(a: Float[jax.Array, " dim"],
                               b: Float[jax.Array, " dim"],
                               c: Float[jax.Array, " dim"]) -> Float[jax.Array, "*"]:
    """Signed area of triangle with vertices a, b, c.

    Parameters
    ----------
    a, b, c : Float[Array, "dim"]
        Triangle vertex positions (dim = 2 or 3).

    Returns
    -------
    Float[Array, "*"]
        Scalar (dim=2) or area-weighted normal vector (dim=3).
        In 2d, positive for counter-clockwise (a, b, c).
    """
    return 0.5 * jnp.cross(b - a, c - a)

def get_triangle_area_from_sides(u: Float[jax.Array, " dim"],
                                 v: Float[jax.Array, " dim"],
                                 ) -> Float[jax.Array, ""]:
    """Unsigned area of triangle edge vectors u, v

    Parameters
    ----------
    u, v : Float[Array, "dim"]
        Triangle edge vectors (any dimension)

    Returns
    -------
    Float[Array, ""]
        Triangle area.
    """
    x = (u**2).sum()*(v**2).sum() - ((u*v).sum())**2
    safe_x = jnp.where(x > 0.0, x, 1.0)
    return jnp.where(x > 0.0, jnp.sqrt(safe_x)/2, 0.0)

def get_triangle_area(a: Float[jax.Array, " dim"],
                      b: Float[jax.Array, " dim"],
                      c: Float[jax.Array, " dim"]) -> Float[jax.Array, ""]:
    """Unsigned area of triangle with vertices a, b, c.

    Parameters
    ----------
    a, b, c : Float[Array, "dim"]
        Triangle vertex positions (any dimension)

    Returns
    -------
    Float[Array, ""]
        Triangle area.
    """
    u, v = b - a, c - a
    return get_triangle_area_from_sides(u, v)


def get_polygon_area(pts: Float[jax.Array, "n_vertices 2"]) -> Float[jax.Array, ""]:
    """Signed area of a 2D simple polygon (shoelace formula).

    Positive for counter-clockwise vertex ordering. This matches the sign
    convention of `get_oriented_triangle_area`.

    Parameters
    ----------
    pts : Float[Array, "n_vertices 2"]
        Ordered polygon vertices.

    Returns
    -------
    Float[Array, ""]
        Signed area.
    """
    return jnp.sum(pts[:, 0] * jnp.roll(pts[:, 1], -1)
                   - jnp.roll(pts[:, 0], -1) * pts[:, 1]) / 2

In [12]:
#| hide 

key1 = jax.random.key(0)
key2 = jax.random.key(1)

a, b = jax.random.normal(key1, shape=2), jax.random.normal(key2, shape=2)
assert get_triangle_area_from_sides(a, b) == jnp.linalg.norm(jnp.cross(a, b))/2

a, b = jax.random.normal(key1, shape=3), jax.random.normal(key2, shape=3)
assert get_triangle_area_from_sides(a, b) == jnp.linalg.norm(jnp.cross(a, b))/2

### Vector operations

In [13]:
#| export

def project_on_vector(a: Float[jax.Array, " dim"], b: Float[jax.Array, " dim"]
                      ) -> Float[jax.Array, " dim"]:
    """Project vector a onto vector b.

    Parameters
    ----------
    a : Float[Array, "dim"]
        Vector to project.
    b : Float[Array, "dim"]
        Target direction.

    Returns
    -------
    Float[Array, "dim"]
        Projection of a onto b.
    """
    return safe_divide(jnp.dot(a, b), jnp.dot(b, b)) * b


def project_out_vector(a: Float[jax.Array, " dim"], b: Float[jax.Array, " dim"]
                       ) -> Float[jax.Array, " dim"]:
    """Project vector a onto the plane orthogonal to b.

    Parameters
    ----------
    a : Float[Array, "dim"]
        Input vector.
    b : Float[Array, "dim"]
        Normal direction to project out.

    Returns
    -------
    Float[Array, "dim"]
        Component of a orthogonal to b.
    """
    return a - safe_divide(jnp.dot(a, b), jnp.dot(b, b)) * b


def get_projector(normal: Float[jax.Array, " dim"]) -> Float[jax.Array, "dim dim"]:
    """Tangent-plane projector $P = I - \\hat{n} \\otimes \\hat{n}$.

    Parameters
    ----------
    normal : Float[Array, "dim"]
        Normal vector (need not be unit length).

    Returns
    -------
    Float[Array, "dim dim"]
        Projection matrix onto the plane orthogonal to normal.
    """
    normal = safe_normalize(normal)
    return jnp.eye(normal.shape[0]) - jnp.outer(normal, normal)


def get_signed_angle_between_vectors(a: Float[jax.Array, "2"], b: Float[jax.Array, "2"]
                                     ) -> Float[jax.Array, ""]:
    """Signed angle from 2D vector a to b (CCW positive).

    Parameters
    ----------
    a, b : Float[Array, "2"]
        2D vectors.

    Returns
    -------
    Float[Array, ""]
        Signed angle in radians, in $(-\\pi, \\pi]$.
    """
    return jnp.atan2(jnp.cross(a, b), jnp.dot(a, b))


def get_angle_between_vectors(a: Float[jax.Array, " dim"], b: Float[jax.Array, " dim"]
                              ) -> Float[jax.Array, ""]:
    """Unsigned angle between vectors a and b.

    Parameters
    ----------
    a, b : Float[Array, "dim"]
        Input vectors. Dimenension 2 or 3.

    Returns
    -------
    Float[Array, ""]
        Angle in radians, in $[0, \\pi]$.
    """
    return jnp.atan2(2*get_triangle_area_from_sides(a, b), jnp.dot(a, b))


def get_cot_between_vectors(a: Float[jax.Array, " dim"], b: Float[jax.Array, " dim"]
                            ) -> Float[jax.Array, ""]:
    """Cotangent of the angle between vectors a and b.

    Parameters
    ----------
    a, b : Float[Array, "dim"]
        Input vectors, any dimension.

    Returns
    -------
    Float[Array, ""]
        Cotangent value.
    """
    denom = 2*get_triangle_area_from_sides(a, b)  # = |a x b| = |a||b| sin(angle)
    return safe_divide(jnp.dot(a, b), denom)

In [14]:
#| export

def get_tetrahedron_volume(a: Float[jax.Array, "3"], b: Float[jax.Array, "3"],
                           c: Float[jax.Array, "3"]) -> Float[jax.Array, ""]:
    """Signed volume of tetrahedron with edge vectors a, b, c from a common vertex.

    Parameters
    ----------
    a, b, c : Float[Array, "3"]
        Edge vectors from a shared origin vertex.

    Returns
    -------
    Float[Array, ""]
        Signed volume (positive if a, b, c form a right-handed frame).
    """
    return jnp.linalg.vecdot(a, jnp.cross(b, c)) / 6

In [15]:
#| hide
get_circumcenter(jnp.array([0.,0.]), jnp.array([0.,1.]),  jnp.array([1.,0.]))

Array([0.5, 0.5], dtype=float64)

In [16]:
#| hide
get_signed_angle_between_vectors(jnp.array([1.,0.]), jnp.array([0.5,0.5])) * (180/jnp.pi)

Array(45., dtype=float64)

In [17]:
#| hide 
get_angle_between_vectors(jnp.array([1.,0.]), jnp.array([0.5,0.5])) * (180/jnp.pi)

Array(45., dtype=float64)

In [18]:
# get_polygon_area is positive for counter-clockwise ordering, and agrees in
# sign and magnitude with get_oriented_triangle_area on triangles.
ccw_tri = jnp.array([[0., 0.], [1., 0.], [0., 1.]])
cw_tri = ccw_tri[::-1]

assert jnp.allclose(get_polygon_area(ccw_tri), 0.5)
assert jnp.allclose(get_polygon_area(cw_tri), -0.5)
assert jnp.allclose(get_polygon_area(ccw_tri), get_oriented_triangle_area(*ccw_tri))
assert jnp.allclose(get_polygon_area(cw_tri), get_oriented_triangle_area(*cw_tri))
assert jnp.allclose(jnp.abs(get_polygon_area(ccw_tri)), get_triangle_area(*ccw_tri))

# counter-clockwise unit square
assert jnp.allclose(get_polygon_area(jnp.array([[0., 0.], [1., 0.], [1., 1.], [0., 1.]])), 1.0)

# translation invariance
assert jnp.allclose(get_polygon_area(ccw_tri + jnp.array([3., -7.])), 0.5)

In [19]:
#| hide
get_circumcenter(jnp.array([1.,0.]), jnp.array([1.,0.]),  jnp.array([0.,1.]))

Array([0., 0.], dtype=float64)

In [20]:
#| hide
get_circumcenter(jnp.array([1.,0.]), jnp.array([2.,0.]),  jnp.array([1.,0.]))

Array([0., 0.], dtype=float64)

### Intrinsic geometry

Many mesh quantities (angles, triangle areas, cotangent weights, circumcenters, ...) can be computed purely intrinsically from edge lengths $\ell_{ij}$, without explicit reference to vertex coordinates.

This matters beyond elegance: whenever vertex positions are unavailable or ambiguous - most importantly under periodic or Lees-Edwards boundary conditions, where a difference of coordinates is meaningless across the boundary - edge lengths are still well defined. The functions below are the single-triangle building blocks; their mesh-level counterparts are in the `geometry` module ("Intrinsic geometry from edge lengths") and the `linops` module.

In [22]:
#| export

def get_triangle_area_from_lengths(la: Float[jax.Array, ""],
                                   lb: Float[jax.Array, ""],
                                   lc: Float[jax.Array, ""]) -> Float[jax.Array, ""]:
    """Triangle area from side lengths using Heron's formula (Kahan's stable form).

    The sides are sorted as $a \\geq b \\geq c$ before evaluating
    $A = \\frac{1}{4}\\sqrt{(a+(b+c))(c-(a-b))(c+(a-b))(a+(b-c))}$. The textbook form
    $\\sqrt{s(s-a)(s-b)(s-c)}$ suffers catastrophic cancellation for thin
    triangles: for a triangle of unit side and height $10^{-8}$ it returns exactly 0
    (float64), which silently deletes the triangle from cotangent weights and areas.

    Returns 0 (with zero gradient, not NaN) when the side lengths violate the triangle
    inequality or describe a degenerate triangle.

    Parameters
    ----------
    la : Float[Array, ""]
        Length of side opposite vertex a (i.e. edge bc).
    lb : Float[Array, ""]
        Length of side opposite vertex b (i.e. edge ca).
    lc : Float[Array, ""]
        Length of side opposite vertex c (i.e. edge ab).

    Returns
    -------
    Float[Array, ""]
        Area of the triangle.
    """
    # sort as a >= b >= c, branch-free and without the (slow) jnp.sort
    hi, lo = jnp.maximum(la, lb), jnp.minimum(la, lb)
    a, b, c = jnp.maximum(hi, lc), jnp.maximum(lo, jnp.minimum(hi, lc)), jnp.minimum(lo, lc)
    radicand = (a + (b + c)) * (c - (a - b)) * (c + (a - b)) * (a + (b - c))
    positive = radicand > 0
    return jnp.where(positive, jnp.sqrt(jnp.where(positive, radicand, 1.0)) / 4, 0.0)


def get_angles_from_lengths(la: Float[jax.Array, ""],
                            lb: Float[jax.Array, ""],
                            lc: Float[jax.Array, ""]) -> Float[jax.Array, "3"]:
    """Interior angles from side lengths.

    Uses $\\theta_a = \\mathrm{atan2}(4A, b^2 + c^2 - a^2)$ with $A$ the triangle area,
    the intrinsic counterpart of `get_angle_between_vectors`. This is accurate for
    angles near 0 and $\\pi$, where $\\arccos$ of the law of cosines loses about half
    the available digits.

    Parameters
    ----------
    la : Float[Array, ""]
        Length of side opposite vertex a (i.e. edge bc).
    lb : Float[Array, ""]
        Length of side opposite vertex b (i.e. edge ca).
    lc : Float[Array, ""]
        Length of side opposite vertex c (i.e. edge ab).

    Returns
    -------
    Float[Array, "3"]
        Angles [alpha, beta, gamma] at vertices a, b, c respectively.
    """
    l2 = jnp.stack([la**2, lb**2, lc**2])               # [a², b², c²]
    l2_opp = jnp.roll(l2, -1) + jnp.roll(l2, -2) - l2   # [b²+c²-a², c²+a²-b², a²+b²-c²]
    return jnp.atan2(4 * get_triangle_area_from_lengths(la, lb, lc), l2_opp)


def get_cotangents_from_lengths(la: Float[jax.Array, ""],
                                lb: Float[jax.Array, ""],
                                lc: Float[jax.Array, ""]) -> Float[jax.Array, "3"]:
    """Cotangents of interior angles from side lengths.

    Uses $\\cot(\\alpha) = (b^2 + c^2 - a^2) / (4 \\cdot \\text{area})$.

    Parameters
    ----------
    la : Float[Array, ""]
        Length of side opposite vertex a (i.e. edge bc).
    lb : Float[Array, ""]
        Length of side opposite vertex b (i.e. edge ca).
    lc : Float[Array, ""]
        Length of side opposite vertex c (i.e. edge ab).

    Returns
    -------
    Float[Array, "3"]
        Cotangents [cot_alpha, cot_beta, cot_gamma] at vertices a, b, c.
    """
    l2 = jnp.stack([la**2, lb**2, lc**2])
    l2_opp = jnp.roll(l2, -1) + jnp.roll(l2, -2) - l2
    area4 = 4 * get_triangle_area_from_lengths(la, lb, lc)
    return safe_divide(l2_opp, area4)


def get_circumcenter_from_lengths(la: Float[jax.Array, ""],
                                  lb: Float[jax.Array, ""],
                                  lc: Float[jax.Array, ""]) -> Float[jax.Array, "3"]:
    """Circumcenter in barycentric coordinates from edge lengths.

    To recover Cartesian coordinates: $u = \\lambda_a \\, a + \\lambda_b \\, b + \\lambda_c \\, c$.

    Parameters
    ----------
    la : Float[Array, ""]
        Length of side opposite vertex a (i.e. edge bc).
    lb : Float[Array, ""]
        Length of side opposite vertex b (i.e. edge ca).
    lc : Float[Array, ""]
        Length of side opposite vertex c (i.e. edge ab).

    Returns
    -------
    Float[Array, "3"]
        Normalized barycentric coordinates [lambda_a, lambda_b, lambda_c].
    """
    ba = la**2 * (lb**2 + lc**2 - la**2)
    bb = lb**2 * (lc**2 + la**2 - lb**2)
    bc = lc**2 * (la**2 + lb**2 - lc**2)
    return safe_divide(jnp.array([ba, bb, bc]), ba + bb + bc)

In [24]:
# Test intrinsic functions against extrinsic (vertex-based) implementations
triangles = [
    jnp.array([[0., 0.], [1., 0.], [0., 1.]]),
    jnp.array([[0., 0.], [3., 0.], [1.5, 2.]]),
    jnp.array([[0., 0., 0.], [1., 0., 0.], [0., 1., 1.]]),
    jnp.array([[1., 2.], [4., 6.], [7., 1.]]),]

for tri in triangles:
    a, b, c = tri
    la, lb, lc = jnp.linalg.norm(b - c), jnp.linalg.norm(c - a), jnp.linalg.norm(a - b)

    # Area
    assert jnp.allclose(get_triangle_area(a, b, c),
                         get_triangle_area_from_lengths(la, lb, lc), atol=1e-10)
    # Angles
    angles_ext = jnp.stack([get_angle_between_vectors(b - a, c - a),
                            get_angle_between_vectors(a - b, c - b),
                            get_angle_between_vectors(a - c, b - c)])
    assert jnp.allclose(angles_ext, get_angles_from_lengths(la, lb, lc), atol=1e-10)

    # Cotangents
    cots_ext = jnp.stack([get_cot_between_vectors(b - a, c - a),
                          get_cot_between_vectors(a - b, c - b),
                          get_cot_between_vectors(a - c, b - c)])
    assert jnp.allclose(cots_ext, get_cotangents_from_lengths(la, lb, lc), atol=1e-10)

    # Circumcenter
    cc_ext = get_circumcenter(a, b, c)
    bary = get_circumcenter_from_lengths(la, lb, lc)
    cc_int = bary[0] * a + bary[1] * b + bary[2] * c
    assert jnp.allclose(cc_ext, cc_int, atol=1e-10)

# Sliver triangles: base 1, height h, so the exact area is h/2. The textbook Heron
# formula returns exactly 0 below h ~ 1e-8 (float64); the stable form does not.
for h in [1e-4, 1e-6, 1e-8]:
    la, lb, lc = jnp.sqrt(0.25 + h**2), jnp.sqrt(0.25 + h**2), jnp.array(1.0)
    assert jnp.isclose(get_triangle_area_from_lengths(la, lb, lc), h / 2, rtol=1e-4), h
    # the two small angles are resolved too (arccos of the law of cosines would not)
    alpha, beta, gamma = get_angles_from_lengths(la, lb, lc)
    assert jnp.isclose(alpha, 2 * h, rtol=1e-4) and jnp.isclose(gamma, jnp.pi - 4 * h, rtol=1e-6), h

# degenerate side lengths: zero area with a finite (zero) gradient, not NaN
assert get_triangle_area_from_lengths(jnp.array(1.), jnp.array(.5), jnp.array(.5)) == 0.0
assert jnp.isfinite(jnp.array(jax.grad(get_triangle_area_from_lengths, argnums=(0, 1, 2))(
    jnp.array(1.), jnp.array(.5), jnp.array(.5)))).all()
# violating the triangle inequality gives 0, not NaN
assert get_triangle_area_from_lengths(jnp.array(5.), jnp.array(1.), jnp.array(1.)) == 0.0

### Rotation matrices and normals

In [25]:
#| export

def get_rot_mat(theta: float) -> Float[jax.Array, "2 2"]:
    """2D counter-clockwise rotation matrix for angle theta.

    Parameters
    ----------
    theta : float
        Rotation angle in radians.

    Returns
    -------
    Float[Array, "2 2"]
        Rotation matrix.
    """
    return jnp.array([[jnp.cos(theta), -jnp.sin(theta)],
                      [jnp.sin(theta), jnp.cos(theta)]])


def get_perp_2d(x: Float[jax.Array, "... 2"]) -> Float[jax.Array, "... 2"]:
    """90-degree clockwise rotation of a 2D vector: $(x, y) \\to (y, -x)$.

    Parameters
    ----------
    x : Float[Array, "... 2"]
        Input vector(s).

    Returns
    -------
    Float[Array, "... 2"]
        Perpendicular vector(s).
    """
    return jnp.stack([x[..., 1], -x[..., 0]], axis=-1)


def get_triangle_normal(a: Float[jax.Array, "3"],
                        b: Float[jax.Array, "3"],
                        c: Float[jax.Array, "3"]) -> Float[jax.Array, "3"]:
    """Unit normal of triangle abc (right-hand rule on a -> b -> c).

    Parameters
    ----------
    a, b, c : Float[Array, "3"]
        Triangle vertex positions.

    Returns
    -------
    Float[Array, "3"]
        Unit normal vector.
    """
    n = jnp.cross(b - a, c - a)
    return safe_normalize(n)


def quaternion_to_rot_mat(q: Float[jax.Array, "4"]) -> Float[jax.Array, "3 3"]:
    """Convert unit quaternion to 3D rotation matrix.

    See `Quaternion rotation <https://en.wikipedia.org/wiki/Quaternions_and_spatial_rotation>`_.

    Parameters
    ----------
    q : Float[Array, "4"]
        Quaternion $[w, x, y, z]$ (normalized internally).

    Returns
    -------
    Float[Array, "3 3"]
        Rotation matrix.
    """
    a, b, c, d = q / jnp.linalg.norm(q)
    return jnp.array([[a**2+b**2-c**2-d**2, 2*b*c-2*a*d, 2*a*c+2*b*d],
                      [2*a*d+2*b*c, a**2-b**2+c**2-d**2, 2*c*d-2*a*b],
                      [2*b*d-2*a*c, 2*a*b+2*c*d, a**2-b**2-c**2+d**2]])

### Barycentric coordinates

In [22]:
#| export

def get_barycentric_coordinates(point: Float[jax.Array, " dim"],
                                a: Float[jax.Array, " dim"],
                                b: Float[jax.Array, " dim"],
                                c: Float[jax.Array, " dim"]) -> Float[jax.Array, "3"]:
    """Barycentric coordinates of point w.r.t. triangle abc.

    Uses the area-ratio method: each coordinate is the ratio of the
    sub-triangle area to the full triangle area. In 3D the point is
    projected onto the triangle plane (least-squares sense).

    Parameters
    ----------
    point : Float[Array, "dim"]
        Query point.
    a, b, c : Float[Array, "dim"]
        Triangle vertex positions.

    Returns
    -------
    Float[Array, "3"]
        Barycentric coordinates [lambda_a, lambda_b, lambda_c] summing to 1.
    """
    v0, v1, v2 = b - a, c - a, point - a
    d00, d01, d11 = jnp.dot(v0, v0), jnp.dot(v0, v1), jnp.dot(v1, v1)
    d20, d21 = jnp.dot(v2, v0), jnp.dot(v2, v1)
    denom = d00 * d11 - d01 * d01
    lb = safe_divide(d11 * d20 - d01 * d21, denom)
    lc = safe_divide(d00 * d21 - d01 * d20, denom)
    return jnp.array([1 - lb - lc, lb, lc])

In [23]:
vertices = jnp.array([[0., 0.], [0., 1.], [1., 0.]])
point1 = jnp.array([0.5, 0.2])

get_barycentric_coordinates(point1, *vertices)

Array([0.3, 0.2, 0.5], dtype=float64)

In [24]:
vertices2 = jnp.array([[0., 0., 0.], [0., 1., 0.], [1., 0., 0.]])
point2 = jnp.array([0.5, 0.2, 0.])

get_barycentric_coordinates(point2, *vertices2)

Array([0.3, 0.2, 0.5], dtype=float64)

In [25]:
point3 = jnp.array([0.5, 0.2, 1.])

get_barycentric_coordinates(point3, *vertices2)

Array([0.3, 0.2, 0.5], dtype=float64)

### Rodrigues rotation

In [26]:
#| export

def rotate_around_axis(v: Float[jax.Array, "3"],
                       axis: Float[jax.Array, "3"],
                       angle: Float[jax.Array, ""]
                       ) -> Float[jax.Array, "3"]:
    """Rotate 3D vector v by angle (radians) around unit axis using Rodrigues' formula.

    Parameters
    ----------
    v : Float[Array, "3"]
        Vector to rotate.
    axis : Float[Array, "3"]
        Unit rotation axis.
    angle : Float[Array, ""]
        Rotation angle in radians.

    Returns
    -------
    Float[Array, "3"]
        Rotated vector.
    """
    return (v * jnp.cos(angle)
            + jnp.cross(axis, v) * jnp.sin(angle)
            + axis * jnp.dot(axis, v) * (1 - jnp.cos(angle)))

In [27]:
# test: rotating x-axis by 90° around z-axis should give y-axis
x = jnp.array([1., 0., 0.])
z = jnp.array([0., 0., 1.])
result = rotate_around_axis(x, z, jnp.array(jnp.pi/2))
assert jnp.allclose(result, jnp.array([0., 1., 0.]), atol=1e-10)

# test: rotating by 0 should return the same vector
assert jnp.allclose(rotate_around_axis(x, z, jnp.array(0.)), x, atol=1e-10)

# test: rotating around the vector itself should return it
v = jnp.array([1., 2., 3.])
axis = v / jnp.linalg.norm(v)
assert jnp.allclose(rotate_around_axis(v, axis, jnp.array(1.23)), v, atol=1e-10)